// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7KPnFE3RkdlIo3EFE_H8RGklLUMlWrc',
    appId: '1:785753121377:web:e9d77c907ade028ae34020',
    messagingSenderId: '785753121377',
    projectId: 'feisty-access-470613-g0',
    authDomain: 'feisty-access-470613-g0.firebaseapp.com',
    storageBucket: 'feisty-access-470613-g0.firebasestorage.app',
    measurementId: 'G-VHQ4E2R7FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJDk-nff8tqI_baru0tgrnRXTUNhfNCQ',
    appId: '1:785753121377:android:307c52c8e688ce2ce34020',
    messagingSenderId: '785753121377',
    projectId: 'feisty-access-470613-g0',
    storageBucket: 'feisty-access-470613-g0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATjLsev2l09KDyt9jdPt09Nfr1FKy_NXY',
    appId: '1:785753121377:ios:ac3412c47ed21872e34020',
    messagingSenderId: '785753121377',
    projectId: 'feisty-access-470613-g0',
    storageBucket: 'feisty-access-470613-g0.firebasestorage.app',
    androidClientId: '785753121377-9idqc1d3q0ql0ehf25a4adc56judsqiq.apps.googleusercontent.com',
    iosClientId: '785753121377-oa7fh20e83gdnvs3gn33j2km63nq56qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATjLsev2l09KDyt9jdPt09Nfr1FKy_NXY',
    appId: '1:785753121377:ios:ac3412c47ed21872e34020',
    messagingSenderId: '785753121377',
    projectId: 'feisty-access-470613-g0',
    storageBucket: 'feisty-access-470613-g0.firebasestorage.app',
    androidClientId: '785753121377-9idqc1d3q0ql0ehf25a4adc56judsqiq.apps.googleusercontent.com',
    iosClientId: '785753121377-oa7fh20e83gdnvs3gn33j2km63nq56qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF7KPnFE3RkdlIo3EFE_H8RGklLUMlWrc',
    appId: '1:785753121377:web:e3b54a04c644e16ce34020',
    messagingSenderId: '785753121377',
    projectId: 'feisty-access-470613-g0',
    authDomain: 'feisty-access-470613-g0.firebaseapp.com',
    storageBucket: 'feisty-access-470613-g0.firebasestorage.app',
    measurementId: 'G-SB8BR05D6E',
  );
}
